common:
  dnsServer: 10.0.0.1
  domain: endor.lab
  galera_password: ladakh1
  haproxy_password: ladakh1
  haproxy_user: birdman
  keystone_admin_password: ladakh1
  keystone_admin_tenant: admin
  keystone_admin_token: ladakh1
  keystone_admin_user: admin
  vip: 10.0.0.254
  vip_mask: 16
registered_services:
  cassandra: []
  collector: []
  config: []
  control: []
  dns: []
  galera: []
  haproxy: []
  openstack: []
  puppet: []
  webui: []
services:
  dns:
    dns1:
      host: 192.168.1.102
      ipaddress: 10.0.0.1/16
      macAddress: de:ad:be:ef:ba:11
    dns2:
      host: 192.168.1.102
      ipaddress: 10.0.0.2/16
      macAddress: de:ad:be:ef:ba:11
  galera:
    gal1:
      host: 192.168.1.102
  haproxy:
    ha1:
      host: 192.168.1.102
    ha2:
      host: 192.168.1.102
  puppet:
    puppet1:
      host: 192.168.1.102
    puppet2:
      host: 192.168.1.102
