common:
  dnsServer: 10.0.0.1
  domain: endor.lab
  keystone_admin_password: ladakh1
  keystone_admin_tenant: admin
  keystone_admin_token: ladakh1
  keystone_admin_user: admin
  vip: 10.0.0.254
  vip_mask: 16
container:
  dns:
    dns1:
      host: 192.168.1.102
      ipaddress: 10.0.0.1/16
      macAddress: de:ad:be:ef:ba:11
  galera:
    gal1:
      host: 192.168.1.102
    password: ladakh1
  haproxy:
    ha1:
      host: 192.168.1.102
    ha2:
      host: 192.168.1.102
      password: ladakh1
      user: birdman
    password: ladakh1
    user: birdman
  puppet:
    puppet1:
      host: 192.168.1.102
    puppet2:
      host: 192.168.1.102
registered_services:
  cassandra: []
  collector: []
  config: []
  control: []
  dns:
  - dns1
  galera: []
  haproxy:
  - ha1
  openstack: []
  puppet:
  - puppet1
  webui: []
