openstack::config::contrail::use_certs: "False"
openstack::config::contrail::cfgm_number: "3"
openstack::config::contrail::uuid: "9e74cfd5-7955-4e9a-a90f-6c1bb943c8c4"
openstack::config::contrail::database_index: "1"
openstack::config::contrail::openstack_index: "1"
openstack::config::contrail::api_nworkers: "1"
openstack::config::contrail::database_initial_token: ""
openstack::config::contrail::bgp_params: ""
openstack::config::contrail::supervisorctl_lines: 'supervisorctl -s http://localhost:9004 ${1} `basename ${0}:0`'
openstack::config::contrail::encap_priority: "VXLAN,MPLSoUDP,MPLSoGRE"
openstack::config::contrail::multi_tenancy: "True"
openstack::config::contrail::cassandra_ip_port: "9160"
openstack::config::contrail::router_asn: "64512"
openstack::config::contrail::database_dir: "/home/cassandra"
openstack::config::contrail::haproxy: "disable"
openstack::config::contrail::rmq_is_master: "no"
openstack::config::contrail::zk_ip_port: "2181"
openstack::config::contrail::vm_ip: ""
openstack::config::contrail::vm_username: "admin"
openstack::config::contrail::vm_passwd: "admin"
openstack::config::contrail::vswitch: ""
openstack::config::contrail::cfgm_index: "1"
openstack::config::contrail::storage_num_osd: 0

#Test configuraion for HA
openstack::config::contrail::redis_ip: "192.168.11.200"
openstack::config::contrail::config_ip: "192.168.11.200"
openstack::config::contrail::collector_ip: "192.168.11.200"
openstack::config::contrail::database_ip: "192.168.11.200"
openstack::config::contrail::amqp_server_ip: "192.168.11.200"
openstack::config::contrail::rmq_master: "control"

openstack::config::contrail::rabbit_user: "[\'rabbit@control\',\'rabbit@control2\',\'rabbit@control3\']"
openstack::config::contrail::control_name_list: ["control", "control2", "control3"]
#TODO(nati) we need 3 node for testing cassandra
openstack::config::contrail::cassandra_ip_list: ["192.168.11.4", "192.168.11.5", "192.168.11.6"]
#openstack::config::contrail::cassandra_ip_list: ["192.168.11.4"]
openstack::config::contrail::control_ip_list: ["192.168.11.4", "192.168.11.5", "192.168.11.6"]
openstack::config::contrail::cassandra_seeds: ["192.168.11.4", "192.168.11.5", "192.168.11.6"]
#openstack::config::contrail::zookeeper_ip_list: ["192.168.11.4"]
openstack::config::contrail::zookeeper_ip_list: ["192.168.11.4", "192.168.11.5", "192.168.11.6"]

#openstack::config::contrail::redis_ip: "192.168.11.4"
#openstack::config::contrail::config_ip: "192.168.11.4"
#openstack::config::contrail::collector_ip: "192.168.11.4"
#openstack::config::contrail::database_ip: "192.168.11.4"
#openstack::config::contrail::amqp_server_ip: "192.168.11.4"
#
#openstack::config::contrail::control_name_list: ["control"]
#openstack::config::contrail::rabbit_user: "['rabbit@control']"
#openstack::config::contrail::cassandra_ip_list: ["192.168.11.4"]
#openstack::config::contrail::control_ip_list: ["192.168.11.4"]
#openstack::config::contrail::cassandra_seeds: ["192.168.11.4"]
#openstack::config::contrail::zookeeper_ip_list: ["192.168.11.4"]

openstack::config::contrail::openstack_root_passwd: ""
openstack::config::contrail::ks_admin_user: "admin"
openstack::config::contrail::ks_admin_tenant: "admin"

openstack::config::contrail::repo_name: "r110build34"
openstack::config::contrail::repo_ip: "192.168.11.3"
openstack::config::contrail::host_roles: ["webui"]
