fixtures:
  repositories:
    "apache": "git://github.com/puppetlabs/puppetlabs-apache.git"
    'concat':
      'repo': 'git://github.com/puppetlabs/puppetlabs-concat.git'
      'ref': '1.2.1'
    "firewall": "git://github.com/puppetlabs/puppetlabs-firewall.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "horizon": "#{source_dir}"
